services:
  minio:
    image: 'ghcr.io/dennisdreissen/minio:latest'
    ports:
      - '29145:9000'
    environment:
      MINIO_ROOT_USER: s3client_integration_tests
      MINIO_ROOT_PASSWORD: s3client_integration_tests
      MINIO_DEFAULT_BUCKETS: >-
        bucket01,
        bucket02,
        list-objects-bucket01,
        list-objects-bucket02,
        list-objects-bucket03,
        list-objects-bucket04
        list-parts-bucket01
        list-parts-bucket02
        list-parts-bucket03
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  default:
    name: s3client_test_network
